---
# main tasks for rpi_fan_adjust role
- name: add poe hat fan speeds to /boot/config.txt
  blockinfile:
    path: /boot/config.txt
    block: |
      dtparam=poe_fan_temp0={{ cpu_temp0 }}
      dtparam=poe_fan_temp1={{ cpu_temp1 }}
      dtparam=poe_fan_temp2={{ cpu_temp2 }}
      dtparam=poe_fan_temp3={{ cpu_temp3 }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR POE HAT FAN SPEEDS"
  ignore_errors: true
- name: reboot cluster
  reboot:
    msg: reboot initiated to apply changes
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_var
- name: action complete
  debug:
    msg: "PoE Fan Adjustments Complete"
- name: reboot required
  debug: 
    msg: "Reboot required for changes to take effect."
  when: not reboot_var
