---
# main tasks for rpi_fan_levels role
- name: add poe hat fan speeds to /boot/config.txt
  blockinfile:
    path: /boot/config.txt
    block: |
      dtparam=poe_fan_temp0={{ fan_level0 }}
      dtparam=poe_fan_temp1={{ fan_level1 }}
      dtparam=poe_fan_temp2={{ fan_level2 }}
      dtparam=poe_fan_temp3={{ fan_level3 }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR POE HAT FAN SPEEDS"
  ignore_errors: true
  
- name: reboot cluster
  reboot:
    msg: reboot initiated to apply changes
    test_command: uptime
  when: reboot_var|bool
  
- name: action complete
  debug:
    msg: "PoE fan adjustments complete"
    
- name: reboot required
  debug: 
    msg: "reboot required for changes to take effect."
  when: not reboot_var|bool
